version: '3.8'

services:
  app:
    build: .
    ports:
      - "3002:3000"
    volumes:
      # Mount source code for live reload (but exclude node_modules)
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env.local
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  node_modules: